---
- name: Create Workload Cluster
  hosts: all
  gather_facts: false
  become: yes
  vars_files:
    - vars/config.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3.11
    kubeconfig_dir: "{{ ansible_env.HOME }}/.rancher-dev/kubeconfigs"
    management_cluster: "management-cluster"
  tasks:
    - name: Create workload cluster
      ansible.builtin.include_role:
        name: cluster_creation_task
      vars:
        cluster: "{{ cluster }}"
