---
servers:
  hosts:
    sponde:
      ansible_host: sponde.prg3.suse.org
      rancher_hostname: sponde.prg3.suse.org
      ansible_user: root
#    kronos:
#      ansible_host: kronos.qa.suse.cz
#      rancher_hostname: kronos.qa.suse.cz
 #     ansible_user: root
  #  erlara:
   #   ansible_host: erlara.qa.suse.cz
     # rancher_hostname: erlara.qa.suse.cz
    #  ansible_user: root
