---
# install_helm.yml
- name: Check Helm installation
  command: /usr/local/bin/helm version --short
  register: helm_check
  changed_when: false
  failed_when: false

- name: Install Helm
  shell: >-
    curl -fsSL https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 |
    HELM_INSTALL_DIR=/usr/local/bin USE_SUDO=false bash ;
    test -x /usr/local/bin/helm
  when: helm_check.rc != 0

- name: Check for helm-diff plugin
  command: /usr/local/bin/helm plugin list
  register: helm_plugin_list
  changed_when: false
  failed_when: false

- name: Ensure broken helm-diff plugin is removed before install
  ansible.builtin.file:
    path: "/root/.local/share/helm/plugins/helm-diff"
    state: absent
  when: "'diff' not in helm_plugin_list.stdout"

- name: Install helm-diff plugin for better idempotency
  command: /usr/local/bin/helm plugin install https://github.com/databus23/helm-diff --version v3.8.1
  when: "'diff' not in helm_plugin_list.stdout"
