---
# install_kubectl.yml
- name: Check current kubectl version
  command: kubectl version --client --output=yaml
  register: kubectl_version_check
  changed_when: false
  failed_when: false

- name: Install kubectl
  get_url:
    url: "https://dl.k8s.io/release/{{ management_cluster_versions.kubernetes }}/bin/linux/amd64/kubectl"
    dest: /usr/local/bin/kubectl
    mode: '0755'
  when: kubectl_version_check.rc != 0 or management_cluster_versions.kubernetes not in kubectl_version_check.stdout
