---
# install_kind.yml
- name: Check current Kind version
  command: kind version
  register: kind_version_check
  changed_when: false
  failed_when: false

- name: Install Kind
  get_url:
    url: "https://kind.sigs.k8s.io/dl/{{ kind_config.version }}/kind-linux-amd64"
    dest: /usr/local/bin/kind
    mode: '0755'
  when: kind_version_check.rc != 0 or kind_config.version not in kind_version_check.stdout
